### ISSUE TITLE
[FEATURE] [forge 1.20.1] Automatic perspective changes

### ISSUE THREAD

**Issue by Aabaddon** [Exopandora/ShoulderSurfing#131]
**Describe your feature**
just as it changes perspective when holding some throwable items it would be nice to make it change into first person when holding building blocks, any building block even modded ones.

and as a quick request could you make the cammera hide the players head sooner? because inside caves and houses it is uncomfortable when it kind of stucks just behind the head without hiding it 

![2023-08-29_23 02 04](https://github.com/Exopandora/ShoulderSurfing/assets/41172599/af14551f-53f9-418e-bec8-0cc50c38dfa6)

**Comment by Exopandora** [comment]
>  just as it changes perspective when holding some throwable items it would be nice to make it change into first person when holding building blocks, any building block even modded ones.

This can be done though the config, although it's very tedious. You need to configure `adaptive_crosshair_items` such that it contains all block that should move you into first person.

> and as a quick request could you make the cammera hide the players head sooner? because inside caves and houses it is uncomfortable when it kind of stucks just behind the head without hiding it

The distance will be configurable in an upcoming version.

**Comment by nwadekoko** [comment]
Hello, I wad about to make the same suggestion for auto switching perspective when holding a list of items. From what you said, if I understand it right, I could add every block I want to be in FPV with in the config, but does that mean it also works the other way and will put me in third person when holding any item that isn't in the list? If so it's already nice to have the option to do it but I would just have a suggestion : couldn't you make it like the feature from Epic fight where we can configure a list in game with auto-add function or manually ? It's one of the feature I miss the most since I'm forced to play with better combat instead. Thanks if you can look into that

**Comment by Exopandora** [comment]
> From what you said, if I understand it right, I could add every block I want to be in FPV with in the config

This is correct. For completeness, the config option was recently split into multiple different ones: `adaptive_crosshair_hold_items` and `adaptive_crosshair_use_items`. You also need to change `crosshair_type` to `STATIC_WITH_1PP` for it to move you in first person.

>  but does that mean it also works the other way and will put me in third person when holding any item that isn't in the list?

It will only put you in first person as long as you are holding or using the item (depending on configuration mentioned above). When you switch back to another item, that is not in the list, it will switch you back in 3rd person.

> couldn't you make it like the feature from Epic fight where we can configure a list in game

You can configre shoulder surfing in-game using other mods, such as [forge config screens](https://www.curseforge.com/minecraft/mc-mods/config-menus-forge).

> with auto-add function or manually ?

I do not use Epic Fight. Could you explain how that works?

**Comment by nwadekoko** [comment]
Hey thank you for the answer, I did a bit of testing while waiting for you and I eventually figured out how it works with the Static with 1pp thing. 
Everything works like a charm it's really the best feature imo.

About the epic fight feature I mentioned, in game when using a mod like ''configured'' or any mod that can edit configs, Epic fight config shows two columns of items, the ones that put you in 3rd person and the ones that put you in first person. There is an auto add button for each list which actually probably just isolate any kind of weapon in the third person column and put everything else (like every block, items, usables, anything not weaponish basically).

So yeah I just took my whole list of things that let me in first person and copy pasted them into your mod's config. That's how I got it to work. Only thing I noticed is that for example if I'm holding a torch in offhand it still counts as me holding the item and since it is in the list, even while having a sword in mainland, I'm still in first person. The solution if I want to remain in third person with any kind of weapon would simply be to remove the Minecraft:torch from the list and then even in offhand with a sword I'd be in third.

I'm so sorry if that isn't very clear, I feel like it is but maybe not as much as needed since I'm really tired right now 😅

Thanks for your time
