### ISSUE TITLE
[BUG] [1.12.2] No player model is displayed

### ISSUE THREAD

**Issue by al-wei** [Exopandora/ShoulderSurfing#154]
### Description

No player model is displayed

ShoulderSurfing-1.12.2-2.9.1

### Steps to Reproduce

no

### Expected Behavior

no

### Screenshots

![image](https://github.com/Exopandora/ShoulderSurfing/assets/145486869/9f1688ae-686a-4f79-be53-d8bd0530dde3)

### Game Logs

no

**Comment by Exopandora** [comment]
Thank you for the report. This looks like a compatibility issue with another mod. Please fill in all the fields of the issue template, otherwise I am not able to fix this issue. You can use [this](https://gist.github.com/TomeWyrm/a8cff19ce112edbc3c8a) method to find the conflicting mod. As a temporary workaroud, you can try setting "Adjust player transparency" to false.

**Comment by al-wei** [comment]
> Thank you for the report. This looks like a compatibility issue with another mod. Please fill in all the fields of the issue template, otherwise I am not able to fix this issue. You can use [this](https://gist.github.com/TomeWyrm/a8cff19ce112edbc3c8a) method to find the conflicting mod. As a temporary workaroud, you can try setting "Adjust player transparency" to false.

Sorry, I forgot about compatibility.
![image](https://github.com/Exopandora/ShoulderSurfing/assets/145486869/ee1aee13-3a67-4e6c-809b-52ecb277d501)

**Comment by Exopandora** [comment]
Please report this issue to the authors of FBP. It works fine with FBP 0.7, but is broken in FBP 0.8. I am suspecting that this is an issue with mixin, as it looks like the changes made by shoulder surfing get completely overridden. There is no known way to me to fix this, other than also using mixins, which i will not invest the time in, to do so for this version.

**Comment by Exopandora** [comment]
You mentioned that it worked with 2.8.x, which got me thinking again. In 2.9.x, some optimizations were made, so code changes to the minecraft code base at runtime will not applied twice, since the code should only load once. But with mixin installed, they load twice. I reverted the optimization change and now it works again. I will release a new version soon, but I want to fix another bug first. Thanks again for reporting!
