### ISSUE TITLE
[BUG] [forge 1.20.1] When i using ShoulderSurfing trims disappears

### ISSUE THREAD

**Issue by Milan4ikdudewtf** [Exopandora/ShoulderSurfing#160]
### Description

It happens with any trimmed armor parts but some trims can be visible at chestplates but only 2-4 pixels and i sure its mods conflict because in my modpack 360+ mods.

### Steps to Reproduce

-

### Expected Behavior

Turning on mod = first screenshot
Turning off mod = second screenshot

### Screenshots

![image](https://github.com/Exopandora/ShoulderSurfing/assets/157549423/80d518d3-2892-4a43-b6ad-0bf1a879f42d)
![image](https://github.com/Exopandora/ShoulderSurfing/assets/157549423/2584925e-6da5-4661-87ef-fadd7822513d)

### Game Logs

https://gist.github.com/Milan4ikdudewtf/3af87e1e4ca8322d5019693740ab074a

**Comment by Exopandora** [comment]
Thanks for the report. Please isolate the conflicting mod using [this](https://gist.github.com/TomeWyrm/a8cff19ce112edbc3c8a) method.

**Comment by Pet-Slime** [comment]
I have also found this issue while using fabric 1.20.1. The mod that seems to be causing a conflict is iris shaders. 

Link to the mod list (which is in a log): https://pastebin.com/LcL6Ztsx

**Comment by Milan4ikdudewtf** [comment]
This is caused by iris or oculus, and I hope you could fix this thing.

**Comment by Exopandora** [comment]
In version 2.9, shoulder surfing introduced the feature of making the player transparent when the view is obstructed. To make this possible, the player rendering had to be adjusted in a way that it supports transparent rendering. The problem is that iris/oculus do transparency sorting, meaning that screen elements are sorted based on the distance to the camera (furthest to nearest) and then drawn in that order. However, iris/oculus assume armor trims to be opaque (hardcoded), while armor rendering is correctly parsed as being transparent (not hardcoded, therefor correctly converted from opqaue to transparent). Due to the aforemetntioned sorting, the armor trims are now being rendered before the armor itselft, making it "invisible" (it is actually behind the armor texture). It took me a while to figure this out. I will see what i can do to fix this sorting issue.
