### ISSUE TITLE
[BUG] [1.20.4] Partially incompatible with Spyglass Improvements

### ISSUE THREAD

**Issue by SplendidAlakey** [Exopandora/ShoulderSurfing#165]
### Description

When using the mod together with [Spyglass Improvements](https://modrinth.com/mod/spyglass-improvements), using the spyglass while in shoulder perspective, the view is obstructed by a solid spyglass texture.

### Steps to Reproduce

1. Just use the spyglass in shoulder perspective

### Expected Behavior

Clear view through the spyglass.

### Screenshots

How it is:
![on](https://github.com/Exopandora/ShoulderSurfing/assets/86702831/fd5483bd-a7d0-41bf-9ae2-59a55c776a25)
How it should be:
![off](https://github.com/Exopandora/ShoulderSurfing/assets/86702831/0eac89bf-4eb2-4710-b1d0-6939509c5897)

### Game Logs

https://gist.github.com/SplendidAlakey/70f1d2f50aa5c42764bf3fbab8a25c9a

### Other Mods

[Spyglass Improvements 1.4](https://modrinth.com/mod/spyglass-improvements/version/1.4+mc1.20.2+fabric)

### Additional Information

The issue only happens with Shoulder Surfing Reloaded 2.9.1+. Version 2.8.1 does not produce the same issue.

**Comment by Exopandora** [comment]
Thanks for the report! Although this bug is fixed, due to other new features coming to Shoulder Surfing Reloaded, it is no longer possible to move around your view in third person when spyglass improvements is installed and looking through a spyglass. This is caused by the way spyglass improvements is implemented, and can only be fixed by its authors. Instead of cancelling the vanilla implementation of `MouseHandler.turnPlayer`, they should only modify the method arguments of `Player.turn` and `Tutorial.onMouse`, or they should modify individual local variables.

**Comment by Exopandora** [comment]
I revised my side of the implementation and there are no more conflicts. juancarloscp52/spyglass-improvements#44 can be closed. The update will be released soon.
