### ISSUE TITLE
Incompatible with Spell Engine and/or Spell Power Attributes [Fabric]

### ISSUE THREAD

**Issue by INooBTooMuch** [Exopandora/ShoulderSurfing#172]
### Description

I tested the "disable half mods and then see etc." but it was weird so this might not be the (only) problem. The 2 mods are libraries or dependencies of another mod [Wizards (RPG Series)](https://www.curseforge.com/minecraft/mc-mods/wizards) (version wizards-fabric-0.9.17+1.19)

It crashes on start so idk, also the mods are beta still for 1.19.2 but did release for 1.20.1

### Minecraft version

1.19.2

### Incompatible mod name

[Spell Engine](https://www.curseforge.com/minecraft/mc-mods/spell-engine) & [Spell Power Attributes [Fabric]](https://www.curseforge.com/minecraft/mc-mods/spell-power)

### Incompatible mod version

spell_engine-fabric-0.9.26+1.19 & spell_power-fabric-0.9.12+1.19

### Game Logs

https://gist.github.com/INooBTooMuch/72bfd21bce22114eacb82a0a75b51e44

**Comment by Exopandora** [comment]
Thanks for the report. Spell engine seems to have an integration plugin for shoulder surfing reloaded, which is outdated since the release of shoulder surfing reloaded 3.0.0. The 1.20.1 version of spell engine has already been updated to incorporate the changes. I will create a pull request over on spell engines repo, to also fix the 1.19 version. The reported issue is also the cause for #170.
