### ISSUE TITLE
Mouse Rotation Not Working Incompatible with EssentialClient 1.2.4

### ISSUE THREAD

**Issue by sdy623** [Exopandora/ShoulderSurfing#180]
### Description

I'm experiencing an issue with the Shoulder Surfing Reloaded mod where the mouse rotation does not work when using the over-the-shoulder camera view. This problem occurs in Minecraft version 1.19.2.

## Expected Behavior
The camera view should rotate in response to mouse movements, allowing for adjustments to the player's field of view.

## Actual Behavior
The camera view remains static and does not respond to any mouse movements, effectively locking the player's field of view.

## Possible Solution
No known workaround at this time.

#179 

### Minecraft version

1.19.2

### Incompatible mod name

EssentialClient

### Incompatible mod version

1.2.4

### Game Logs

https://mclo.gs/Pey0YQI

**Comment by Exopandora** [comment]
Update essential client, the bug is not present in later versions.

**Comment by sdy623** [comment]
@Exopandora I changed the EssentialClient 1.3.2 is still get errors
here is the log https://mclo.gs/PqYa1ZU#L6

**Comment by Exopandora** [comment]
Sorry, I made an error while testing. You are correct that the issue still persists. Unfortunately, it looks like that there is no good way of solving the issue, as both EssentialClient and Shoulder Surfing Reloaded need to modify the exact same method (see [here](https://github.com/senseiwells/EssentialClient/blob/1.19.x/src/main/java/me/senseiwells/essentialclient/mixins/clientScript/ClientPlayerEntityMixin.java#L65) and [here](https://github.com/Exopandora/ShoulderSurfing/blob/1.19.2/common/src/main/java/com/github/exopandora/shouldersurfing/mixins/MixinLocalPlayer.java#L21)), in order to implement their features. Both methods cannot co-exist.

**Comment by Exopandora** [comment]
I could raise the priority of shoulder surfings implementation, so you would be able to turn again, however, this would break the player look hook of EssentialClient scripts.

**Comment by Exopandora** [comment]
The partial fix is now available in the latest version. There is not much else i can do. Closing for now.
