### ISSUE TITLE
Can't hit to grass and planted seeds

### ISSUE THREAD

**Issue by bahtsizz** [Exopandora/ShoulderSurfing#183]
I can hit to grass and planted seeds on first person and game's perspective options but i can't while on shoulder surfing mod's perspective. I don't want to use some automated seed planter with right click. I don't know if this is a thing to prevent camera glitching on long grass. I already checked the config file but if there is a config or something can yall please help me fix this?
(Btw my game has mods so it can be a compatibility issue.)

Game Version: 1.20.1 Fabric

Edit: It's a compatibility issue. I'm currently trying to find what mod it is.

Edit 2: The mod causing this problem was MedievalWeapons. It was not that necessary for me but it could have been having support for it.

**Comment by Exopandora** [comment]
The problem is that MedievalWeapons adds the "minecraft:throwing" property to every item. This tricks shoulder surfing reloaded into thinking that you are aiming all the time, because "minecraft:throwing" is configured to be included by default as `adaptive_crosshair_use_item_properties`. When "aiming", shoulder surfing reloaded ignores blocks without collisions (for example, tall grass) for a better aiming experience. As a workaround, you could remove "minecraft:throwing" from the `adaptive_crosshair_use_item_properties` list.
