### ISSUE TITLE
Incompatible with MOD Time Clock

### ISSUE THREAD

**Issue by Satsu1312** [Exopandora/ShoulderSurfing#208]
### Description

Shoulder surfing has a bug in the cameras with the mod time stop clock;
When you run the command /timeclock pauseTime true, It does not allow you to do any action on the camera with shoulder surfing, in previous versions before incorporating the option of uncoupled camera could, As such I think it is not a bug, but it is an incompatibility and I would like to know if you can fix it :)

### Minecraft version

1.20.1

### Incompatible mod name

Time stop clock

### Incompatible mod version

1.1.0

### Game Logs

https://mclo.gs/dVMme0p

**Comment by Exopandora** [comment]
Thank you for the report. I tested version 4.0.0 of Shoulder Surfing Reloaded, which was released yesterday. Everything seems to work normally, except for player turning when attacking, interacting, etc. and the camera distance interpolation. The issue seems to be caused by time clock preventing the minecraft client from ticking properly. The fact that time clock is closed source does not make things easier. I suggest reporting the issue on their issue tracker over on curseforge, as there is nothing I can currently do about this problem. If you do not use the item of time clock, I suggest using the tick command of fabric-carpet or a forge port of fabric-carpet instead.

**Comment by Satsu1312** [comment]
Hey sorry, I think I saw when it happens concretely!!!, When you set the camera up, I mean with the crosshair, the camera wobbles, I think it is what you mention to interpolation of the distance of the camera, is there any way to disable this so that the wobble does not occur with the mod? here's a video
https://streamable.com/o1tv4r

**Comment by Exopandora** [comment]
> When you set the camera up, I mean with the crosshair, the camera wobbles, I think it is what you mention to interpolation of the distance of the camera, is there any way to disable this so that the wobble does not occur with the mod?

This is exactly what I meant. But there are more things that do not work. I will not bend my usage of the forge api just to make it compatible with a mod that does not follow the rules of the framework.

**Comment by Satsu1312** [comment]
Oh okay, thanks for replying :)
