### ISSUE TITLE
[1.15.2] Conflicts with optifine

### ISSUE THREAD

**Issue by Iam5B** [Exopandora/ShoulderSurfing#21]
Here are my mods:
preview_OptiFine_1.15.2_HD_U_G1_pre13.jar
MixinBootstrap-1.0.2.jar
OptiForge-MC1.15.2-0.1.10.jar
ShoulderSurfing-1.15.2-1.22.4.jar

**Comment by Exopandora** [comment]
OptiFine compatibility will be added when OptiFine is compatible with forge versions

**Comment by Exopandora** [comment]
sp614x/optifine#3898

**Comment by Exopandora** [comment]
cpw/modlauncher#37

**Comment by Exopandora** [comment]
Shoulder Surfing should now work with optifine except shaders and 3PP crosshair.

**Comment by RainEffect** [comment]
![bug image](https://user-images.githubusercontent.com/14258727/102122908-26f18d80-3e81-11eb-9197-f664397ace8c.jpg)
Image of this bug.

**Comment by Exopandora** [comment]
Please report this to the optifine developer

**Comment by drThunderbuckle** [comment]
I am having the same issue as RainEffect. It does not seem to be an optifine bug because it only happens while I am using shoulder surfing third person.
![2021-01-09_10 59 05](https://user-images.githubusercontent.com/66651208/104103850-00e5c000-526a-11eb-94fe-93fa2fb9d72c.png)
Shoulder Surfing
![2021-01-09_10 59 10](https://user-images.githubusercontent.com/66651208/104103857-0d6a1880-526a-11eb-9e86-73168d46417a.png)
Normal 3rd Person
