### ISSUE TITLE
[ERROR in SERVER CONSOLE] ShoulderSurfing + Third Person Shooting: Zero

### ISSUE THREAD

**Issue by DaDiGui** [Exopandora/ShoulderSurfing#212]
### Description

The two mods work correctly ingame, they do their purpose which is to add a 3 person camera and to be able to switch between 1 and 3 person. Those errors in console I don't know if it's Arclight's fault or I would have to report it in their respective mods. 
BUT WORKS WELL INGAME

### Steps to Reproduce

1. Install the two mods
2. Start the server
3. Wait for the errors to appear in the console.

### Minecraft version

1.20.1

### Game Logs

https://mclo.gs/WfsHXIv

### Additional Information

Java is version 17.0.3
https://github.com/IzzelAliz/Arclight/issues/1377

**Comment by Exopandora** [comment]
You are getting this error because Third Person Shooting is trying to load a compatibility plugin for Shoulder Surfing Reloaded. But since you are in a server environment, where Shoulder Surfing Reloaded is not supposed to be installed, it fails loading some components of minecraft, because they are not present on a server.
