### ISSUE TITLE
Bring back disconnected camera option

### ISSUE THREAD

**Issue by ultimatejacob27** [Exopandora/ShoulderSurfing#224]
The decoupled option only lets me switch between a free camera with a fixed player orientation (Idk why I would choose this, I need the ability to turn) and making the player always orient towards the camera. If this behavior is sounding like a bug, then feel free to change the label. I want the ability to rotate the camera freely without the player turning, and for the player to rotate in the direction of movement. It was also nice when there was an option so that interacting with something would cause the player to rotate in the direction of the camera.

**Comment by Exopandora** [comment]
This looks like you are having a compatibility issue. My first guess is that it is caused by MedievalWeapons. Please refer to the [compatibility section](https://github.com/Exopandora/ShoulderSurfing?tab=readme-ov-file#compatibility) on how to solve the problem. If the issue is present without any other mods installed, please consider opening a new issue using the "Bug Report" template. If it turns out to be a specific incompatibility with another mod, please open a new issue using the "Compatibility Issue" template.
