### ISSUE TITLE
help wanted with camera

### ISSUE THREAD

**Issue by user128587348** [Exopandora/ShoulderSurfing#236]
i see other users of this mod with a locked camera yet mine goes all around my body i need help fixing it because i cant find the solution to this problem could you please help me out.

Uploading Minecraft_ 1.19.2 - Singleplayer 2024-08-01 23-59-23.mp4…

**Comment by Exopandora** [comment]
This is most likely a compatibility issue with better first person. Uninstall it and it should work. Otherwise, create a new compatibility issue using the [provided template](https://github.com/Exopandora/ShoulderSurfing/issues/new?assignees=&labels=compatibility&projects=&template=compatibility.yaml&title=Incompatible+with+MOD). The template will help you to find the root cause and provides necessary information for me to diagnose the issue.

**Comment by user128587348** [comment]
> This is most likely a compatibility issue with better first person. Uninstall it and it should work. Otherwise, create a new compatibility issue using the [provided template](https://github.com/Exopandora/ShoulderSurfing/issues/new?assignees=&labels=compatibility&projects=&template=compatibility.yaml&title=Incompatible+with+MOD). The template will help you to find the root cause and provides necessary information for me to diagnose the issue.

**Comment by user128587348** [comment]
> > This is most likely a compatibility issue with better first person. Uninstall it and it should work. Otherwise, create a new compatibility issue using the [provided template](https://github.com/Exopandora/ShoulderSurfing/issues/new?assignees=&labels=compatibility&projects=&template=compatibility.yaml&title=Incompatible+with+MOD). The template will help you to find the root cause and provides necessary information for me to diagnose the issue.

I am not using better first person though??

**Comment by user128587348** [comment]
Im not using better first person

**Comment by Exopandora** [comment]
Please create a new compatibility issue using the [provided template](https://github.com/Exopandora/ShoulderSurfing/issues/new?assignees=&labels=compatibility&projects=&template=compatibility.yaml&title=Incompatible+with+MOD). The template will help you to find the root cause and provides necessary information for me to diagnose the issue. Without that information, I will not be able to help you any further.
