### ISSUE TITLE
Epic Fight "lock on" mode

### ISSUE THREAD

**Issue by Joe-Schmoe-123** [Exopandora/ShoulderSurfing#239]
### Description

Epic Fight has a lock on mode that keeps your player facing a selected enemy.  Shoulder Surfing doesn't rotate with the locked on direction but keeps you facing straight ahead as your player turns to face the enemy {you need to try it to see what I'm talking about).  It would be great if the third person camera rotated with the player's direction. 

### Minecraft version

1.20.1

### Incompatible mod name

Epic FIght

### Incompatible mod version

20.7.4

### Game Logs

https://mclo.gs/0FMKA5W

**Comment by Exopandora** [comment]
Thanks for reporting! Can you please describe in more detail what you mean by lockon or how to trigger it? Maybe a video would be helpful.

**Comment by Joe-Schmoe-123** [comment]
It's triggered by facing an enemy and hitting G.  It locks your perspective on to a target so that as you or they move you constantly face the enemy.

**Comment by Exopandora** [comment]
The camera now rotates with the player when in lock-on mode and camera is coupled. If you want the lock-on mode to rotate the camera even when the camera is decoupled, you need to make the following change in `common/src/main/java/com/github/exopandora/shouldersurfing/compat/mixins/epicfight/MixinRenderEngine.java` and build from source:
```diff
			((AccessorCamera) camera).invokeSetRotation(yRot, xRot);
		}
-		else if(!Config.CLIENT.isCameraDecoupled())
+		else
		{
			ShoulderSurfingImpl.getInstance().getCamera().setXRot(xRot);
```

**Comment by Joe-Schmoe-123** [comment]
Thank you!  This is my favorite mod and you are great at responding to user feedback,

**Comment by ClixzyFN** [comment]
> The camera now rotates with the player when in lock-on mode and camera is coupled. If you want the lock-on mode to rotate the camera even when the camera is decoupled, you need to make the following change in `common/src/main/java/com/github/exopandora/shouldersurfing/compat/mixins/epicfight/MixinRenderEngine.java` and build from source:
> 
> ```diff
> 			((AccessorCamera) camera).invokeSetRotation(yRot, xRot);
> 		}
> -		else if(!Config.CLIENT.isCameraDecoupled())
> +		else
> 		{
> 			ShoulderSurfingImpl.getInstance().getCamera().setXRot(xRot);
> ```

i still get the issue on the lastest version on 1.20.1

**Comment by Farenheith** [comment]
Hello!

@ClixzyFN, @Exopandora, I've been trying an abandoned mod, https://github.com/Maxmani/lock-on, which I cloned and observed the same problem. The catch is that the concept of locking on requires a coupled perspective; otherwise, the math of the camera locking on doesn't match up.

As I'd cloned the repo and adapted it to Minecraft 1.21.4, I also changed it, making ShoulderSurfing a dependency of it, and then changed the code to couple the camera every time I have a locked target and decouple it when the lock is lost. The result looked natural, as seen in the video below.

https://github.com/user-attachments/assets/2e987cb6-c635-448a-9b9d-1c496a4f5ced

I haven't tried to do the change you've suggested, as your mod is up to date with the latest Minecraft version and is well maintained, so I'd rather use it as it is, but I suspect unwanted some side effects may happen from removing this if, otherwise it wouldn't be needed at all.
