### ISSUE TITLE
Commands for Camera Adjustments

### ISSUE THREAD

**Issue by oksimvey** [Exopandora/ShoulderSurfing#246]
Would be really amazing if u made commands to adjust the camera x, y, and z set. would help a lot to devs that want make dynamic adjustments, like when the player is riding a horse, when player is fightning with a big mob, etc

**Comment by Exopandora** [comment]
Thank you for the suggestion. I'm assuming you want to use command blocks or data packs in order to control the camera offsets for certain areas. This creates the following problem: Command blocks and data packs run on the logical server, whereas Shoulder Surfing Reloaded only runs on the logical client. Somehow, the server would need to communicate the changes to the client, which would require the mod to be installed on the server. This is a fundamental change that I do not want to do. As an alternative, I would recommend creating a simple companion mod, that uses the [Shoulder Surfing Reloaded API](https://github.com/Exopandora/ShoulderSurfing/wiki/API-Documentation-Getting-Started) in order to change the camera offsets depending on the situation. You can use the [ITargetCameraOffsetCallback](https://github.com/Exopandora/ShoulderSurfing/wiki/API-Documentation-Callbacks#itargetcameraoffsetcallback) for that.
