### ISSUE TITLE
[Feature request] Turn view with boat turning like in vanilla third person

### ISSUE THREAD

**Issue by antieksi** [Exopandora/ShoulderSurfing#247]
One of the features of the vanilla third person is player view rotating with the boat. It works the same in the first person. Though, somehow, it doesn't work that way in the shoulder surfing mode: view always stays in the same place regardless of the boat rotation. It would be nice to have this as a separate setting.

Also it'd be good to have the camera centering when riding boat the same way as when using elytra or when climbing,
because passenger multipliers act a bit weird and are making my player transparent in shoulder surfing mode.

**Comment by Exopandora** [comment]
Thank you for the feedback! Please create seprate issues for separate topics next time :) 

> One of the features of the vanilla third person is player view rotating with the boat. It works the same in the first person. Though, somehow, it doesn't work that way in the shoulder surfing mode: view always stays in the same place regardless of the boat rotation. It would be nice to have this as a separate setting.

This is indeed a good point. I implemented the feature for the coupled camera mode in 6549787. The decoupled camera mode is unaffected.

> Also it'd be good to have the camera centering when riding boat the same way as when using elytra or when climbing,
because passenger multipliers act a bit weird and are making my player transparent in shoulder surfing mode.

From your message, I'm reading that you want to suggest a config option called "center_camera_when_passenger". Such a config option is not necessary, as the passenger modifiers and multipliers do the **exact same** thing (set `camera.offset.multiplier.passenger.multiplier_offset_x` to `0.0`), but also give you the possibility to also adjust the y and z axis. The player becomes transparent because `player.adjust_player_transparency` is set to `true` in the config, and the crosshair overlaps with the player's hitbox. The player als becomes transparent when `center_camera_when_climbing` or `center_camera_when_fall_flying` are enabled. You can prevent this by changing the modifiers and/or multipliers in such a way, that the crosshair does not overlaps with the player's hitbox (0.3 x-offset, after all modifiers and multipliers have been applied).

**Comment by Exopandora** [comment]
Closing this for now. If you still think that your requested feature is not fully implemented, please open up another issue.
