### ISSUE TITLE
[BUG]keep_camera_out_of_head_distance_multiplier = 0

### ISSUE THREAD

**Issue by TakimotoEirlo** [Exopandora/ShoulderSurfing#257]
#The distance multiplier on whether or not to hide the player model if the camera gets too close to it. Set to 0 to disable.
	#Range: 0.0 ~ 1.7976931348623157E308
	keep_camera_out_of_head_distance_multiplier = 0

??

This didn't work.
![2024-12-17_22 15 21](https://github.com/user-attachments/assets/a3aee8fc-0aee-41cf-8c55-75a4e2b4471a)

1.21.1 fabric

**Comment by Exopandora** [comment]
The setting you are looking for is "adjust_player_transparency". Please use the appropiate issue template next time when you report an issue.

**Comment by TakimotoEirlo** [comment]
> 您要查找的设置是“adjust_player_transparency”。下次报告问题时请使用适当的问题模板。

What I mean is that setting it to "0" doesn't work.

**Comment by Exopandora** [comment]
## How `keep_camera_out_of_head_distance_multiplier` works

When set to `0` : The player model is still visible, no matter how close you get with the camera. (`adjust_player_transparency` is set to `true` for this demonstration):
![image](https://github.com/user-attachments/assets/d3f61e23-fdc4-468a-9330-afd3c45651f6)

When set to `0.75`: The player model is not rendered, because the camera is closer than 0.75 blocks to the player:
![image](https://github.com/user-attachments/assets/91f595cb-9de1-4a67-a4a3-7667b7ebd5ec)

## How `adjust_player_transparency` works

When set to `true`: The player model is always rendered at maximum opacity. (`keep_camera_out_of_head_distance_multiplier` is set to `0` for this demonstration):
![image](https://github.com/user-attachments/assets/4f1571b2-ef15-4431-9ce7-33bb709b38b4)

When set to `false`: The player model is rendered with varying transparency . (`keep_camera_out_of_head_distance_multiplier` is set to `0` for this demonstration):
![image](https://github.com/user-attachments/assets/d3f61e23-fdc4-468a-9330-afd3c45651f6)
