### ISSUE TITLE
Request: Toggle 3pp override

### ISSUE THREAD

**Issue by lilgandhi1199** [Exopandora/ShoulderSurfing#4]
So you just took a request and added a fourth option in f5 (which is your mode) instead of replacing 3pp like you used to do it but by doing so I lost the ability to spectate my friends with your awesome over the shoulder perspective using "picture in picture" (a buddycam mod). Now it's back to the miles away horribly un-exciting perspective because it can only take advantage of 3pp and not the newly relocated  4th entry...

**Comment by lilgandhi1199** [comment]
Btw you did actually make the xray scope smaller. Before even at -22 without view bobbing It would sit comfortably like 3 blocks into the wall lol! Now it's not until 24.5 before even a single pixel is visible. I wanted to make sure you knew that you did make it much much better.

**Comment by Exopandora** [comment]
To 1: The problem is that the code injection takes place before the mod loads (it could be possible though). I cannot tell at this point if you want it to be a replaced version or a new added 3pp.
To 2: In the previous version (1.8) i accidentally left in one piece of code where i tried (or more like played around with) to fix this very bug (even before you reported). It added (1, 0, 0) to the players position and was therefore even more buggy than 1.7 (thats why its alpha now).

**Comment by Exopandora** [comment]
Actually it would be possible

**Comment by Exopandora** [comment]
Added feature for 1.10

**Comment by lilgandhi1199** [comment]
Thanks very much!
https://imgur.com/a/gS1JR
