### ISSUE TITLE
1.12.2 no over-the-shoulder view

### ISSUE THREAD

**Issue by RavioliWpesto** [Exopandora/ShoulderSurfing#47]
is it possible to change the position of the cursor in 3rd person mode when in the 1.12.2 release? I don't like how the cursor is inside the player model, and I was wondering if I was missing a config option somwhere

**Comment by Exopandora** [comment]
What do you mean by "cursor is inside the player model"? Do you mean that the crosshair moves on screen or that the camera is inside the player?

**Comment by Pry0** [comment]
Yeah I get the same issue where this happens:
https://ibb.co/Y2m2XsC

This isn't the default minecraft third person btw.

**Comment by Exopandora** [comment]
Please provide the resulting crash log from pressing `F3` + `C` for 10 seconds while ingame.

**Comment by Exopandora** [comment]
Note: You are supposed to set it up yourself with the keybinds. The unadjusted shoulder surfing view is basically just the vanilla third person view.

**Comment by ubergarm** [comment]
I must say `Shoulder Surfing Reloaded` is amazing especially that it supports real-time ray tracing `adaptive crosshairs`!

Still works great in 1.12.2 in my opinion, here is the config file I'm using in my latest modpack [7 Days to Fly](https://www.curseforge.com/minecraft/modpacks/seven-days-to-fly)

https://github.com/ubergarm/7DaysToFly/blob/master/config/shouldersurfing.cfg

You can see how I scooted over the camera a bit with:
```
    # Third person camera x-offset
    D:x-offset=-0.85
```

It works so well with `Epic Fight` mod that I am considering replacing Vic's guns w/ Tech Guns (because Vic's disables the cross-hairs for "realism"...)

Anyway, cheers! this issue seems closable to me...

**Comment by Exopandora** [comment]
SSR 1.12.2 was completely redone after this issues was submitted. Therefore  this issue is no longer applicable for the latest releases. If this issue still persists in the latest version please open up a new issue.
