### ISSUE TITLE
Crosshairs vanish in First Person with Better Combat Rebirth

### ISSUE THREAD

**Issue by estradus** [Exopandora/ShoulderSurfing#7]
Title sums it up, I think.  The crosshairs exist fine in the over the shoulder view, but vanish in first person.  They work fine without Better Combat Rebirth and without Shoulder Surfing, its just using them in tandem that causes problems.  

Minecraft 1.12.2
forge both 2765 and 2770
Shoulder surfing version they dont seem to be labeled, the august release
better combat rebirth 1.12.2 - 1.5.6

**Comment by Exopandora** [comment]
The SoulderSurfing version is labeled 1.13. Better Combat Rebirth uses the same event (https://github.com/SanAndreasP/BetterCombatRebirth/blob/master/src/main/java/bettercombat/mod/client/handler/EventHandlersClient.java#L59) Shoulder Surfing uses (https://github.com/Exopandora/ShoulderSurfing/blob/master/src/main/java/com/teamderpy/shouldersurfing/ShoulderEventHandler.java#L128) to modify the crosshair. Both mods cancel the event after they ran their own code so no other mods (and minecraft) will be able render their modified crosshair (because there already is one). This is a hard issue to fix. Maybe its not even possible because of the additional 3pp mode from Shoulder Surfing.

**Comment by Exopandora** [comment]
Fixed with version 1.12.2-1.14
