### ISSUE TITLE
Over the shoulder when using the dynamic reticle after adding the player EX MOD will cause the HUD to shift

### ISSUE THREAD

**Issue by ainlzj** [Exopandora/ShoulderSurfing#84]
1.16.5   2.2.10

![TXZ7YES_)TCCNPA}A15BQVX](https://user-images.githubusercontent.com/66135518/184902162-fe98d6a0-d463-4014-a9f8-500a607f7b78.png)

**Comment by Exopandora** [comment]
Please fill in all the details of the issue temple: https://github.com/Exopandora/ShoulderSurfing/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by ainlzj** [comment]
https://www.curseforge.com/minecraft/mc-mods/playerex    playerex

Only the FORGE version of playerexMOD is added, then select the dynamic crosshair and then shake the mouse gui to move, just like the picture

**Comment by ainlzj** [comment]
forge

**Comment by Exopandora** [comment]
It looks like this is not fixable in a good way. The best solution would be that playerex cleans up their code in order to prevent this bug because the mod renders gui twice for some reason. But i doubt that it will be fixed as it seems like they dropped support for forge. If you are only using playerex in combination with shouldersurfing you might want to try the fabric version of both, this might fix the issue.
