### ISSUE TITLE
[BUG] [1.18.2 Fabric] Raytrace compatibility issue with WTHIT/Jade/Hywla/Waila

### ISSUE THREAD

**Issue by ardissaps** [Exopandora/ShoulderSurfing#85]
Is it possible to make hovered crosshair are the one that displayed? I will try to post on WTHIT sides too.
![image](https://user-images.githubusercontent.com/82106625/185286947-80539f2e-7daa-450a-9062-2d0ce3305960.png)

**Comment by deirn** [comment]
WTHIT raycasts the object manually since what vanilla provide from `Minecraft#hitResult` is not configurable, it also doesn't pick dropped item and has a bigger hitbox for other entities.

For this issue I added an API to replace the raycasting method, [`IObjectPicker`](https://github.com/badasintended/wthit/blob/5.11.0/src/api/java/mcp/mobius/waila/api/IObjectPicker.java). The default impl is [`ObjectPicker`](https://github.com/badasintended/wthit/blob/5.11.0/src/pluginCore/java/mcp/mobius/waila/plugin/core/pick/ObjectPicker.java). Use 4.13.0 for Minecraft 1.18.2.

**Comment by Exopandora** [comment]
Thank you for the quick support! I will create a plugin for it later. I also have another idea: You could implement a config option to use the vanilla hitResult which would enable direct support for ssr without any updates.

**Comment by ardissaps** [comment]
Hello again!  @Exopandora, the mods is working great with WTHIT, thank you very much! Only 1 thing that does not work with new raytrace, liquid bucket. When we want to pur liquid both lava and water, it does not fill the one on the crosshair in 3rd person. Tried on both forge and fabric. No hurry, take your time, have a nice day! :)

**Comment by Exopandora** [comment]
Thanks for the report! This is now fixed in a new version. If you encounter any other issues please open up a new issue.

**Comment by ardissaps** [comment]
Ok! It works great now, thanks!
