### ISSUE TITLE
[Kibe Gliders glitch]

### ISSUE THREAD

**Issue by AriaThePeryton** [Exopandora/ShoulderSurfing#98]
### Description

Game would crash if character hits a wall while in third person with Kibe's gliders (Kibe Utilities ver. 1.9.10)

### Steps to Reproduce

-Use a Kibe Glider
-shoulder surf
-hit a wall (or anthing for that matter

### Expected Behavior

Crashing to desktop

### Game Logs

<script src="https://gist.github.com/AriaThePeryton/a1e6d2139e40eb6d284b05f986c0f69e.js"></script>

### Other Mods

Kibe Utilities 1.9.10-BETA

**Comment by badcrave** [comment]
Hello! I am experiencing the same issue, I have more details! 

**Steps to Reproduce**

- make sure "keep out of head" is enabled
- Use gliders from Kibe Utilies
- Enter the shoulder surfing perspective 
- crash into a wall or do anything that causes the camera to attempt to shift to first person

**Expected behaviour**
- Camera switches to first person without crashing, but instead the game crashes
